### ISSUE TITLE
PIF Creation as a library

### ISSUE THREAD

**Issue by fake-name** [gfcwfzkm/PIF-Image-Format#1]
I'm working on a project where I want to have a server component (python) that ships images to a embedded LCD system (based around a ESP32).

Currently, I'm just using raw bitmaps, but this project looks like it'd be pretty handy. On the other hand, the current code for generating PIF images only seems to live *in the converter GUI file*. 

This seems like the kind of thing that should be extracted out to a proper library, and be available somewhere like PyPi. Or at minimum in a separate file so it can be somewhat easily vendored. 

I'd be happy to handle setting all that up, if you're OK with that, but I don't want to just jump in and start pushing stuff to PyPi without at least talking first.

**Comment by gfcwfzkm** [comment]
That is something I am looking into my self, but sadly lacked the time to dive into it due to lack of python knowledge and moving places.

I'd be okay with you handling this and setting it up, while also taking the chance to learn more about the library side of things within python and how PyPi (or similar) works for such.

Likely would make it more straight-forward to develop a command line converter tool in the future as well.
