### ISSUE TITLE
Kaitai Struct specification

### ISSUE THREAD

**Issue by armijnhemel** [gfcwfzkm/PIF-Image-Format#5]
FYI, support for parsing PIF was added to Kaitai Struct a little while ago, see:

https://github.com/kaitai-io/kaitai_struct_formats/blob/master/image/pif.ksy

**Comment by gfcwfzkm** [comment]
Thanks for informing me about this. I didn't know such a neat tool like Katai Struct existed!
I haven't looked into their code output of the PIF format in detail, it seems to parse the file correctly but lack RLE-support to decode the data straight away. Still a solid point if someone wants to get started with it, I'd say.

**Comment by generalmimon** [comment]
@gfcwfzkm:

> I haven't looked into their code output of the PIF format in detail, it seems to parse the file correctly but lack RLE-support to decode the data straight away.

That's OK - it's not meant to decode the pixel data. It just takes care of the metadata and the color table, which is already quite useful, and this is where PIF differs from other image formats. After the metadata is parsed, decoding the actual pixels is relatively simple - in some cases, you can pass the entire bitmap to an existing image manipulation library (if it uses a common pixel format like RGB888) and it's not so hard to do it manually, either - probably just 1-2 `for` loops with some `if`s.

A better support for bitmaps in Kaitai Struct has been proposed (https://github.com/kaitai-io/kaitai_struct/issues/188) and would be nice to have. Although it's probably possible to fully describe all the pixels using [user-defined types](https://doc.kaitai.io/user_guide.html#types) in Kaitai Struct already now, in practice it's not a very good idea, because it would be a very time- and memory-inefficient (one class instance per pixel or even color component) and a user of the parser would still have to iterate the pixel objects and translate them into a more useful representation of a bitmap, so it wouldn't really save much work either.

**Comment by armijnhemel** [comment]
> Thanks for informing me about this. I didn't know such a neat tool like Katai Struct existed! I haven't looked into their code output of the PIF format in detail, it seems to parse the file correctly but lack RLE-support to decode the data straight away. Still a solid point if someone wants to get started with it, I'd say.

I sent it so if you want you can include it in the README :-)

**Comment by gfcwfzkm** [comment]
@armijnhemel
Thanks, I'll definitely add it to the README! :)

@generalmimion
So there is progress towards fully reading bitmap data! That would make it quite the allround-tool for quick and easy image decoding capabilities (next to the already impressive feature set).
